openapi: 3.1.0
info:
  title: Send Chapter to Make
  description: Send written chapters to Make.com for editing, scoring, and publishing.
  version: 1.0.0
servers:
  - url: https://hook.eu2.make.com/xqbt89a96i0g9o2qd8jkjot2faxrqk2l
paths:
  /:
    post:
      operationId: sendChapter
      summary: Send a complete chapter (fused from part 1 and part 2)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapterNumber
                - title
                - content
              properties:
                chapterNumber:
                  type: string
                  description: The chapter number (e.g., "Chapter 4")
                title:
                  type: string
                  description: The chapter title (e.g., "The Burning Sky")
                content:
                  type: string
                  description: The full chapter content (fused from part 1 and part 2)
                notes:
                  type: string
                  description: Optional notes or comments (e.g., "Unedited draft")
      responses:
        '200':
          description: Chapter successfully received
